# Generated by Django 4.2.6 on 2023-10-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60, verbose_name='Name')),
                ('email', models.CharField(max_length=200)),
                ('messagge', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Message',
            },
        ),
        migrations.RemoveField(
            model_name='filterthirsection',
            name='urls',
        ),
    ]
