# Generated by Django 4.2.6 on 2023-10-22 13:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contentfirstsection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentfirstsection',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='contentfirstsection',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contentsecondsection',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Title'),
        ),
    ]
