# Generated by Django 5.1 on 2024-09-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_card_img_card_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='img',
            field=models.ManyToManyField(blank=True, related_name='cards', to='home.img', verbose_name='Image'),
        ),
    ]
