# Generated by Django 5.1 on 2024-09-08 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_card_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='front_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.img', verbose_name='Images'),
            preserve_default=False,
        ),
    ]
