# Generated by Django 5.1 on 2024-09-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_card_url_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
